### PR TITLE
add procfile and alter post script

### PR DESCRIPTION
**Pull request by dubhcait**
relates #30 

Added Procfile for Heroku - as start script is cd server && npm start
Altered Postscript to navigate out of server directory. 

Just going to try to deploy the branch and check for errors

### CODE REVIEW

**Comment by dubhcait** [comment]
A Node.js app on Heroku requires a 'package.json' at the root of the directory structure. is still an error, unfortunately. So to fix this I think we have to move the package.json to root unless anyone olse has any ideas?

**Comment by AbdallahAmmar96** [comment]
ok, @dubhcait
first thing go to the client folder and run the script npm run build
you will see the build folder has appeared in the client folder, take it and then put it in the server folder
then you just deploy the server folder at Heroku

**Comment by AbdallahAmmar96** [comment]
and you deploy only the server folder

**Comment by AbdallahAmmar96** [comment]
another solution: 
move the package.json from the server to the root and edit the scripts 
and this will make auto-deploy with every push on GitHub

**Comment by dubhcait** [comment]
cool I'll do the second solution and test that branch as

**Pull request closed without merging**
